In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set_theme(style='darkgrid')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')
raw_data.head(5)

/tmp/ipykernel_1245/669193869.py:1: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6

In [3]:
raw_data.columns

Index(['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod',
       'tamb', 'lab_temp', 'pflow', 'psamp', 'ploop', 'pamb', 'CH4_rt',
       'CH4_w', 'CH4_ht', 'CH4_area', 'CH4_skew', 'CH4_start_time',
       'CH4_end_time', 'CH4_start_level', 'CH4_end_level', 'CH4_Rl_ht',
       'CH4_Rl_a', 'CH4_Rl', 'CH4_norm_ht', 'CH4_norm_a', 'CH4_norm_w',
       'CH4_R_ht', 'CH4_R_a', 'CH4_R', 'CH4_C_ht', 'CH4_C_a', 'CH4_C',
       'CH4_std_stdev', 'CH4_std_rep', 'CH4_Cstd', 'CH4_flag_ht', 'CH4_flag_a',
       'CH4_flag', 'CH4_flag_p', 'CH4_flag_ht_bin', 'CH4_flag_a_bin', 'label1',
       'datetime_str', 'datetime', 'is_ht_999', 'is_area_999', 'is_rt_zero',
       'is_w_zero', 'duration', 'is_duration_spike', 'baseline_drift',
       'ht_area_ratio', 'last_std_time', 'seconds_since_last_std', 'type_std',
       'type_air', 'type_tank', 'type_blank', 'type_cal', 'type_other',
       'last_cal_time', 'seconds_since_last_cal', 'year', 'month', 'day',
       'hour', 'minute', 'seconds', 'psamp_roll_mean_10', 'pamb_roll_mean_10',
       'pflow_roll_mean_10', 'tmod_roll_mean_10', 'psamp_roll_mean_100',
       'pamb_roll_mean_100', 'pflow_roll_mean_100', 'tmod_roll_mean_100',
       'psamp_roll_std_10', 'pamb_roll_std_10', 'pflow_roll_std_10',
       'CH4_rt_roll_std_10', 'psamp_roll_std_100', 'pamb_roll_std_100',
       'pflow_roll_std_100', 'CH4_rt_roll_std_100', 'psamp_diff_1',
       'pflow_diff_1', 'CH4_area_diff_1', 'psamp_lag_1', 'pflow_lag_1'],
      dtype='object')

In [4]:
data = raw_data.copy()
data = data.drop(data[data['year']==2026].index)
data.tail()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1
808206,251231,223800,std,J-286,J-286,3,0.0,40.0,21.01,NaN,817.8,765.45,NaN,765.7,94.0,7.83,170066.0,1489856.0,1.16,80.8,133.4,23823.0,24073.0,1.00099,1.00067,1.00067,1.0010,1.0007,0.9997,1.00099,1.00067,1.00067,2017.92,2017.27,2017.27,2.406,NaN,2015.923,,,A,,0,0,0,251231223800,2025-12-31 22:38:00,False,False,False,False,52.6,False,250.0,0.114149,2025-12-31 21:57:00,2460.0,1,0,0,0,0,0,2025-12-28 06:16:00,318120.0,2025,12,31,22,38,0,766.407,766.33,816.44,40.0,772.0808,772.056,822.436,40.0,0.583306,0.586989,2.761320,0.10328,2.832881,2.881439,3.691583,0.094516,-0.47,-4.6,34189.0,765.37,813.7
808207,251231,225800,air,9m,J-286,1,9.0,40.0,20.74,NaN,813.2,765.28,NaN,765.2,94.0,7.85,171821.0,1508117.0,1.16,80.8,133.4,23750.0,24058.0,1.01178,1.01300,1.01300,1.0118,1.0130,1.0014,1.01178,1.01300,1.01300,2039.67,2042.12,2042.12,2.396,2.427,2015.923,,,A,,0,0,0,251231225800,2025-12-31 22:58:00,False,False,False,False,52.6,False,308.0,0.113931,2025-12-31 21:57:00,3660.0,0,1,0,0,0,0,2025-12-28 06:16:00,319320.0,2025,12,31,22,58,0,766.222,766.18,816.24,40.0,771.9890,771.966,822.381,40.0,0.561581,0.528730,2.555691,0.10328,2.897443,2.938020,3.719446,0.095219,0.08,4.1,-34481.0,765.45,817.8
808208,251231,231800,std,J-286,J-286,3,0.0,40.0,20.88,NaN,817.5,765.08,NaN,764.9,94.2,7.84,169569.0,1487622.0,1.06,80.8,133.6,23740.0,24030.0,0.99744,0.99876,0.99876,0.9973,0.9986,1.0015,0.99744,0.99876,0.99876,2010.76,2013.42,2013.42,2.413,NaN,2015.923,,,A,,0,0,0,251231231800,2025-12-31 23:18:00,False,False,False,False,52.8,False,290.0,0.113987,2025-12-31 22:38:00,2400.0,1,0,0,0,0,0,2025-12-28 06:16:00,320520.0,2025,12,31,23,18,0,766.039,766.00,816.19,40.0,771.8964,771.871,822.240,40.0,0.537720,0.524934,2.615106,0.10328,2.962336,3.001626,3.797527,0.095874,-0.17,-4.6,18261.0,765.28,813.2
808209,251231,233800,air,9m,J-286,1,9.0,40.0,20.79,NaN,813.3,765.05,NaN,765.0,94.2,7.86,170281.0,1496142.0,1.07,80.8,133.6,23756.0,24015.0,1.00289,1.00503,1.00503,1.0030,1.0051,1.0021,1.00289,1.00503,1.00503,2021.75,2026.06,2026.06,2.401,2.413,2015.923,,,A,,0,0,0,251231233800,2025-12-31 23:38:00,False,False,False,False,52.8,False,259.0,0.113813,2025-12-31 22:38:00,3600.0,0,1,0,0,0,0,2025-12-28 06:16:00,321720.0,2025,12,31,23,38,0,765.872,765.82,816.02,40.0,771.8028,771.775,822.179,40.0,0.551519,0.565292,2.447584,0.10328,3.028294,3.069445,3.824358,0.095874,-0.20,4.3,-20495.0,765.08,817.5
808210,251231,235800,std,J-286,J-286,3,0.0,NaN,NaN,NaN,817.4,764.90,NaN,NaN,94.2,7.83,169985.0,1489453.0,1.09,80.8,133.4,23691.0,24015.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.415,NaN,2015.923,,,A,,0,0,0,251231235800,2025-12-31 23:58:00,False,False,False,False,52.6,False,324.0,0.114126,2025-12-31 23:18:00,2400.0,1,0,0,0,0,0,2025-12-28 06:16:00,322920.0,2025,12,31,23,58,0,765.710,765.66,815.82,40.0,771.7077,771.680,822.040,40.0,0.528520,0.546097,2.590495,0.10328,3.089538,3.130656,3.892028,0.095874,-0.03,-4.2,8520.0,765.05,813.3

In [5]:
feature_cols = [
    #'sample'	,'standard',	
    #'port'	,'ht',
    'tmod'	,'tamb',
    'pflow', 'psamp',
    'pamb'	,
    'CH4_rt',	'CH4_w',	'CH4_ht'	,
    'CH4_area',	'CH4_skew'	,
    'CH4_start_time',	'CH4_end_time'	,'CH4_start_level',	'CH4_end_level',
    #'CH4_Rl_ht',	'CH4_Rl_a',	'CH4_Rl',	
    #'CH4_norm_ht','CH4_norm_a',	'CH4_norm_w',
    #'CH4_R_ht','CH4_R_a', 'CH4_R'	,'
    #'CH4_C_ht'	,'CH4_C_a',	'CH4_C',	
    # std
    #'CH4_std_rep', 'CH4_std_rep'
    #'CH4_Cstd', 
    #'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero',
    'duration', 
    #'is_duration_spike',
    #'baseline_drift', 
    'ht_area_ratio',
    #'type_air', 'type_blank', 'type_cal', 'type_other', 'type_std', 'type_tank',
    #'year', 'month', 'day', 'hour', 'minute', 'seconds'
]

In [6]:
# 
def types_convert(type_name):
    """
    This fnuction is used for type classification
    """
    t = str(type_name).lower().strip()

    if 'cal' in t:
        return 'cal'
    elif 'std' in t:
        return 'std'
    elif 'air' == t:
        return 'air'
    elif 'tank' in t:
        return 'tank'
    elif 'blank' in t:
        return 'blank'
    else:
        return 'other'

In [7]:
data['type_norm'] = data['type'].apply(types_convert)
data['type_norm'].unique()

array(['air', 'std', 'tank', 'cal', 'blank', 'other'], dtype=object)

In [8]:
print(1)

1

In [ ]:
print(2)