In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')
raw_data.head(5)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

/tmp/ipykernel_46984/1576195687.py:4: DtypeWarning: Columns (37) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_data = pd.read_csv('../data/processed/mhd_ch4_ml_v2.csv')

In [2]:
raw_data['year'].unique()

array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026])

In [3]:
raw_data = raw_data.drop(raw_data[raw_data['year']==2026].index)

In [4]:
raw_data['year'].unique()

array([1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [5]:
years = sorted(raw_data['year'].unique())
years

[np.int64(1994),
 np.int64(1995),
 np.int64(1996),
 np.int64(1997),
 np.int64(1998),
 np.int64(1999),
 np.int64(2000),
 np.int64(2001),
 np.int64(2002),
 np.int64(2003),
 np.int64(2004),
 np.int64(2005),
 np.int64(2006),
 np.int64(2007),
 np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016),
 np.int64(2017),
 np.int64(2018),
 np.int64(2019),
 np.int64(2020),
 np.int64(2021),
 np.int64(2022),
 np.int64(2023),
 np.int64(2024),
 np.int64(2025)]

In [6]:
df = raw_data.copy()

In [7]:
df.head()

,date,time,type,sample,standard,port,ht,tmod,tamb,lab_temp,pflow,psamp,ploop,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,CH4_Rl_ht,CH4_Rl_a,CH4_Rl,CH4_norm_ht,CH4_norm_a,CH4_norm_w,CH4_R_ht,CH4_R_a,CH4_R,CH4_C_ht,CH4_C_a,CH4_C,CH4_std_stdev,CH4_std_rep,CH4_Cstd,CH4_flag_ht,CH4_flag_a,CH4_flag,CH4_flag_p,CH4_flag_ht_bin,CH4_flag_a_bin,label1,datetime_str,datetime,is_ht_999,is_area_999,is_rt_zero,is_w_zero,duration,is_duration_spike,baseline_drift,ht_area_ratio,last_std_time,seconds_since_last_std,type_std,type_air,type_tank,type_blank,type_cal,type_other,last_cal_time,seconds_since_last_cal,year,month,day,hour,minute,seconds,psamp_roll_mean_10,pamb_roll_mean_10,pflow_roll_mean_10,tmod_roll_mean_10,psamp_roll_mean_100,pamb_roll_mean_100,pflow_roll_mean_100,tmod_roll_mean_100,psamp_roll_std_10,pamb_roll_std_10,pflow_roll_std_10,CH4_rt_roll_std_10,psamp_roll_std_100,pamb_roll_std_100,pflow_roll_std_100,CH4_rt_roll_std_100,psamp_diff_1,pflow_diff_1,CH4_area_diff_1,psamp_lag_1,pflow_lag_1
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,841.9,761.10,NaN,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216142900,1994-02-16 14:29:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,29,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,840.4,761.07,NaN,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216144900,1994-02-16 14:49:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,14,49,0,761.100000,761.100000,841.900000,40.000000,761.100000,761.100000,841.900000,40.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,761.10,841.9
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,839.4,760.99,NaN,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216150900,1994-02-16 15:09:00,False,False,False,False,33.4,False,-34.0,0.384554,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,9,0,761.085000,761.150000,841.150000,40.000000,761.085000,761.150000,841.150000,40.000000,0.021213,0.070711,1.060660,0.000000,0.021213,0.070711,1.060660,0.000000,-0.03,-1.5,0.0,761.07,840.4
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,839.6,760.96,NaN,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,,,,,0,0,0,940216152900,1994-02-16 15:29:00,False,False,False,False,42.8,False,0.0,0.142279,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,15,29,0,761.053333,761.066667,840.566667,40.003333,761.053333,761.066667,840.566667,40.003333,0.056862,0.152753,1.258306,63.393060,0.056862,0.152753,1.258306,63.393060,-0.08,-1.0,496440.0,760.99,839.4
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,845.4,760.72,NaN,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,,1,1,1,940216180000,1994-02-16 18:00:00,False,False,True,True,0.0,False,0.0,NaN,NaN,NaN,0,1,0,0,0,0,NaN,NaN,1994,2,16,18,0,0,761.030000,761.025000,840.325000,40.002500,761.030000,761.025000,840.325000,40.002500,0.065828,0.150000,1.135415,59.379542,0.065828,0.150000,1.135415,59.379542,-0.03,0.2,569542.0,760.96,839.6

In [8]:
cols_all = [
    #'sample'	,'standard',	
    'port'	,'ht',
    'tmod'	,'tamb',
    'pflow', 'psamp',
    'pamb'	,
    'CH4_rt',	'CH4_w',	'CH4_ht'	,
    'CH4_area',	'CH4_skew'	,
    'CH4_start_time',	'CH4_end_time'	,'CH4_start_level',	'CH4_end_level',
    #'CH4_Rl_ht',	'CH4_Rl_a',	'CH4_Rl',	
    #'CH4_norm_ht','CH4_norm_a',	'CH4_norm_w',
    #'CH4_R_ht','CH4_R_a', 'CH4_R'	,'
    #'CH4_C_ht'	,'CH4_C_a',	'CH4_C',	
    # std
    #'CH4_std_rep', 'CH4_std_rep'
    #'CH4_Cstd', 
    #'is_ht_999', 'is_area_999', 'is_rt_zero', 'is_w_zero',
    'duration', 
    #'is_duration_spike',
    #'baseline_drift', 
    'ht_area_ratio',
    'type_air', 'type_blank', 'type_cal', 'type_other', 'type_std', 'type_tank',
    'year', 'month', 'day', 'hour', 'minute', 'seconds'
    #'psamp_lag_1',	'psamp_lag_2'	,'pflow_lag_1'	,'pflow_lag_2'	,'tmod_lag_1',	
    #'tmod_lag_2',	'tamb_lag_1',	'tamb_lag_2',	'CH4_rt_lag_1',	'CH4_rt_lag_2'	,
    #'CH4_w_lag_1'	,'CH4_w_lag_2',	'CH4_ht_lag_1'	,'CH4_ht_lag_2'	,'CH4_area_lag_1',
    #'CH4_area_lag_2'	,'CH4_skew_lag_1'	,'CH4_skew_lag_2',	'psamp_roll_std_10',	
    #'psamp_roll_std_100'	,'psamp_roll_mean_10'	,'psamp_roll_mean_100',
    #'pflow_roll_std_10'	,'pflow_roll_std_100',	'pflow_roll_mean_10',	
    #'pflow_roll_mean_100'	,'tmod_roll_std_10'	,'tmod_roll_std_100',	
    #'tmod_roll_mean_10'	,'tmod_roll_mean_100',	'tamb_roll_std_10'	,
    #tamb_roll_std_100',	'tamb_roll_mean_10','tamb_roll_mean_100',	
    #'CH4_rt_roll_std_10',	'CH4_rt_roll_std_100',	'CH4_rt_roll_mean_10',	
    #'CH4_rt_roll_mean_100'
]

In [9]:
df = df[cols_all]
df.head()

,port,ht,tmod,tamb,pflow,psamp,pamb,CH4_rt,CH4_w,CH4_ht,CH4_area,CH4_skew,CH4_start_time,CH4_end_time,CH4_start_level,CH4_end_level,duration,ht_area_ratio,type_air,type_blank,type_cal,type_other,type_std,type_tank,year,month,day,hour,minute,seconds
0,3,10.0,40.00,32.27,841.9,761.10,761.1,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,NaN,1,0,0,0,0,0,1994,2,16,14,29,0
1,3,10.0,40.00,32.48,840.4,761.07,761.2,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,NaN,1,0,0,0,0,0,1994,2,16,14,49,0
2,3,10.0,40.01,32.75,839.4,760.99,760.9,109.8,2.60,190908.0,496440.0,0.63,102.0,135.4,10063.0,10029.0,33.4,0.384554,1,0,0,0,0,0,1994,2,16,15,9,0
3,3,10.0,40.00,32.92,839.6,760.96,760.9,94.8,6.85,151667.0,1065982.0,1.02,86.2,129.0,99999.0,99999.0,42.8,0.142279,1,0,0,0,0,0,1994,2,16,15,29,0
4,3,10.0,40.00,33.31,845.4,760.72,760.6,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,NaN,1,0,0,0,0,0,1994,2,16,18,0,0

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 808211 entries, 0 to 808210
Data columns (total 30 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   port             808211 non-null  int64
 1   ht               808211 non-null  float64
 2   tmod             695927 non-null  float64
 3   tamb             695926 non-null  float64
 4   pflow            805809 non-null  float64
 5   psamp            805881 non-null  float64
 6   pamb             805807 non-null  float64
 7   CH4_rt           806621 non-null  float64
 8   CH4_w            806621 non-null  float64
 9   CH4_ht           806621 non-null  float64
 10  CH4_area         806621 non-null  float64
 11  CH4_skew         806621 non-null  float64
 12  CH4_start_time   806621 non-null  float64
 13  CH4_end_time     806621 non-null  float64
 14  CH4_start_level  806621 non-null  float64
 15  CH4_end_level    806621 non-null  float64
 16  duration         806621 non-null  float64
 17  ht_area_ratio    789934 non-null  float64
 18  type_air         808211 non-null  int64
 19  type_blank       808211 non-null  int64
 20  type_cal         808211 non-null  int64
 21  type_other       808211 non-null  int64
 22  type_std         808211 non-null  int64
 23  type_tank        808211 non-null  int64
 24  year             808211 non-null  int64
 25  month            808211 non-null  int64
 26  day              808211 non-null  int64
 27  hour             808211 non-null  int64
 28  minute           808211 non-null  int64
 29  seconds          808211 non-null  int64
dtypes: float64(17), int64(13)
memory usage: 185.0 MB

In [28]:
import pandas as pd
from sklearn import datasets
    
from evidently import Dataset
from evidently import DataDefinition
from evidently import Report
from evidently.presets import DataDriftPreset, DataSummaryPreset

In [41]:
schema = DataDefinition(
    numerical_columns=[	'port',	'ht',	'pflow'	,
                       'psamp',	'pamb',	'CH4_rt',	'CH4_w'	,
                       'CH4_ht'	,'CH4_area'	,'CH4_skew'	,
                       'CH4_start_time'	,'CH4_end_time',	'CH4_start_level',	
                       'CH4_end_level'	,'duration',	'ht_area_ratio'],

    categorical_columns=['type_air'	,'type_blank'	,'type_cal'	,'type_other',	
                       'type_std', 'type_tank', 'port'],
    )

In [49]:
reports = {}
for i in range(len(years)-1):
    y1 = years[i]
    y2 = years[i+1]

    reference =  Dataset.from_pandas(
        pd.DataFrame(df[df['year'] == y1].drop(columns=['tamb','tmod','year', 'month', 'day',	'hour', 'minute', 'seconds'])),
        data_definition=schema
    )
    current = Dataset.from_pandas(
        pd.DataFrame(df[df['year'] == y2].drop(columns=['tamb','tmod','year', 'month', 'day',	'hour', 'minute', 'seconds'])),
        data_definition=schema
    )

    report = Report([
    DataDriftPreset(
        num_method='wasserstein',
        num_threshold=0.1
    ) 
])

    my_eval = report.run(reference, current)
    my_eval.save_html(f'html/{y1}to{y2}.html')

===============0621

In [22]:
import pandas as pd
from evidently import Report
from evidently import Dataset, DataDefinition
from evidently.descriptors import Sentiment, TextLength, Contains
from evidently.presets import TextEvals, DataDriftPreset

drift_scores = []

for i in range(len(years)-1):
    y1 = years[i]
    y2 = years[i+1]

    reference = df[df['year'] == y1].drop(columns=['year'])
    current = df[df['year']==y2].drop(columns=['year'])

    report =Report([DataDriftPreset()])
    report.run(reference_data=reference, current_data=current)

    result_dict = report.dict()
    drift_detected = result_dict['metrics'][0]['result']['dataset_drift']
    drift_scores.append((y1, y2, drift_detected))
print(drift_scores)

AttributeError: 'Report' object has no attribute 'dict'

In [19]:
from evidently.column_mapping import ColumnMapping

ModuleNotFoundError: No module named 'evidently.column_mapping'

In [ ]:
data_columns = ColumnMapping()
data_columns.numerical_features = ['weather', 'temp', 'atemp', 'humidity', 'windspeed']

In [ ]:
from evidently import Report
from evidently.presets import DataDriftPreset

drift_scores = []

for i in range(len(years)-1):
    y1 = years[i]
    y2 = years[i+1]

    reference = df[df['year'] == y1].drop(columns=['year'])
    current = df[df['year']==y2].drop(columns=['year'])

    data_drift_report = Report(metrics=[DataDriftPreset()])
    data_drift_report.run(reference_data=reference, current_data=current column_mapping=data_columns)
    report = data_drift_report.as_dict()
    report =Report([DataDriftPreset()])

    report.run(reference_data=reference, current_data=current)

    drift_result = report.metrics[0].get_result()
    drift_detected = drift_result.dataset_drift
    drift_scores.append((y1, y2, drift_detected))
print(drift_scores)