# convert csv file into parquet file 
import polars as pl
import time

csv_filename = "../data/processed/tac_ch4_formatted_v1.csv"
parquet_filename = "../data/processed/tac_ch4_formatted_v1.parquet"

lazy_df = pl.scan_csv(csv_filename)
lazy_df.sink_parquet(parquet_filename)

In [1]:
# features
import duckdb

parquet_filename = "../data/processed/tac_ch4_formatted_v1.parquet"
duckdb.sql(f"DESCRIBE SELECT * FROM '{parquet_filename}'").df()

     column_name column_type null   key default extra
0           date      BIGINT  YES  None    None  None
1           time      BIGINT  YES  None    None  None
2           type     VARCHAR  YES  None    None  None
3         sample     VARCHAR  YES  None    None  None
4       standard     VARCHAR  YES  None    None  None
5           port      BIGINT  YES  None    None  None
6            dry      DOUBLE  YES  None    None  None
7            wet      DOUBLE  YES  None    None  None
8          stdev      DOUBLE  YES  None    None  None
9        std_rep     VARCHAR  YES  None    None  None
10     std_stdev     VARCHAR  YES  None    None  None
11  target_error     VARCHAR  YES  None    None  None
12        Cdrift      DOUBLE  YES  None    None  None
13             C      DOUBLE  YES  None    None  None
14             N      BIGINT  YES  None    None  None
15     Nfiltered      DOUBLE  YES  None    None  None
16        time.1      DOUBLE  YES  None    None  None
17           h2o      DOUBLE  YES  None    None  None
18       stdev.1      DOUBLE  YES  None    None  None
19         press      DOUBLE  YES  None    None  None
20   press_stdev      DOUBLE  YES  None    None  None
21          temp      DOUBLE  YES  None    None  None
22    temp_stdev      DOUBLE  YES  None    None  None
23        temp.1      DOUBLE  YES  None    None  None
24        temp.2      DOUBLE  YES  None    None  None
25        temp.3     VARCHAR  YES  None    None  None
26         valve      DOUBLE  YES  None    None  None
27      CH4_flag     VARCHAR  YES  None    None  None

In [4]:
duckdb.sql(f"SELECT * FROM '{parquet_filename}'USING SAMPLE 10 ROWS").df()

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,CH4_flag
0,120902,10730,air,54m,USN-20112109,8,1909.801,1902.995,0.775,0.388,...,0.00269,140.01724,0.04764,45.00012,0.00014,35.78029,44.98263,None,31092.412,x
1,120902,103030,air,54m,USN-20112109,8,1920.292,1913.371,0.760,0.39,...,0.00048,139.99886,0.01983,45.00011,0.00020,36.31250,44.98189,None,31114.824,
2,121128,4530,air,100m,USN-20112109,9,1911.611,1907.570,0.435,0.308,...,0.00046,139.99612,0.01240,44.99999,0.00010,34.58823,44.98957,None,31175.555,
3,121129,94830,air,100m,USN-20112109,9,1901.718,1898.040,0.499,0.289,...,0.00050,140.00421,0.02023,44.99963,0.00024,33.94764,44.99032,None,31120.602,
4,121130,211430,air,54m,USN-20112109,8,2167.843,2164.036,3.681,0.325,...,0.00037,140.00612,0.01324,44.99932,0.00023,33.80121,44.99090,None,31225.562,
5,130813,221530,air,100m,USN-20112109,9,1903.847,1898.971,0.246,0.26,...,NaN,140.00124,0.00739,44.99952,0.00031,35.36515,45.00177,None,31308.877,
6,130815,4230,air,100m,USN-20112109,9,1874.682,1868.941,1.412,0.261,...,0.00072,139.99608,0.01080,44.99973,0.00018,36.85489,45.00194,None,31318.469,
7,130817,120730,air,185m,USN-20112109,10,1921.127,1913.750,0.600,0.314,...,NaN,139.99678,0.01303,45.00019,0.00008,37.50024,45.00190,None,31334.662,
8,131106,51930,air,185m,USN-20112109,10,1920.748,1915.931,1.237,0.33,...,0.00047,139.99936,0.01651,44.99962,0.00017,35.74351,45.00562,None,31470.080,
9,140129,35330,air,54m,USN-20112109,8,1938.862,1934.726,0.226,0.253,...,0.00050,140.00204,0.01872,45.00040,0.00028,35.88973,45.01035,None,31569.609,

In [9]:
duckdb.sql(f"SELECT * FROM '{parquet_filename}' LIMIT 5").df()

,date,time,type,sample,standard,port,dry,wet,stdev,std_rep,...,stdev.1,press,press_stdev,temp,temp_stdev,temp.1,temp.2,temp.3,valve,CH4_flag
0,120111,162730,unknown,-,USN-20112109,0,1944.517,1945.109,42.208,None,...,0.00175,140.00525,0.01396,44.90277,0.01251,32.14167,44.77072,None,31442.617,x
1,120111,162830,unknown,-,USN-20112109,0,1972.043,1972.643,57.714,None,...,0.00170,140.00435,0.01518,44.92952,0.00415,32.36250,44.91882,None,31543.971,x
2,120111,162930,unknown,-,USN-20112109,0,1940.176,1940.768,65.419,None,...,0.00221,140.00513,0.01176,44.93352,0.00128,32.59792,44.99702,None,31626.549,x
3,120111,163030,unknown,-,USN-20112109,0,2021.915,2022.526,80.016,None,...,0.00256,140.00745,0.01437,44.92616,0.00253,32.81506,45.02549,None,31687.379,x
4,120111,163130,unknown,-,USN-20112109,0,1976.217,1976.825,57.151,None,...,0.00192,140.00314,0.01321,44.91914,0.00165,32.98813,45.02443,None,31726.805,x