In [4]:
pd.set_option('display.max_columns', None)

In [1]:
import pandas as pd
#可以把這邊改成classs，然後一進來就直接根據他選的地方去做預測
#===========================

def parse_mhd_file(file_path):
    parsed_rows = []

    flag_total_len = 28

    with open(file_path, 'r', encoding='utf-8') as f:
        #skip header
        lines = f.readlines()

    header_line = lines[2].rstrip('\r\n')

    header_data_part = header_line[:-flag_total_len ]
    header_flag_part = header_line[-flag_total_len:]

    data_headers = header_data_part.strip().split()
    flag_headers = [
        header_flag_part[0:8].strip(),
        header_flag_part[8:16].strip(),
        header_flag_part[16:21].strip(),
        header_flag_part[21:28].strip()
    ] 

    feature_names = data_headers + flag_headers
    print(feature_names)

    df_mhd=pd.read_fwf(
    file_path,
    skiprows=1,
    header=1,
    keep_default_na=False
    )



    df_mhd.columns = feature_names

    # read the file in the way that the flag space is right

    df_mhd_data = pd.read_csv(file_path, skiprows=1, sep=r'\s+',header=1, engine='python') # skip first row, txt is space seperated
    #這邊是為了 把flag和真實的data放一起，所以各只取flag 和flag以外的數值
    df_mhd_data.columns = feature_names

    real_data_mhd = df_mhd_data.iloc[:, :-4]

    df_mhd_flag = df_mhd.iloc[:, -4:]

    df_mhd_flag.index = real_data_mhd.index 
    real_data_mhd = pd.concat([real_data_mhd, df_mhd_flag], axis=1)
        
    return real_data_mhd

In [2]:
file_path = '../data/raw/mhd_ch4.txt'
mhd_df = parse_mhd_file(file_path)
mhd_df.head()

['date', 'time', 'type', 'sample', 'standard', 'port', 'ht', 'tmod', 'tamb', 'temp', 'pflow', 'psamp', 'ploop', 'pamb', 'rt', 'w', 'ht', 'area', 'skew', 'start_time', 'end_time', 'start_level', 'end_level', 'Rl_ht', 'Rl_a', 'Rl', 'norm_ht', 'norm_a', 'norm_w', 'R_ht', 'R_a', 'R', 'C_ht', 'C_a', 'C', 'std_stdev', 'std_rep', 'Cstd', 'flag_ht', 'flag_a', 'flag', 'flag_p']

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
0,940216,142900,air,10m,G-024,3,10.0,40.00,32.27,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
1,940216,144900,air,10m,G-024,3,10.0,40.00,32.48,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
2,940216,150900,air,10m,G-024,3,10.0,40.01,32.75,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,
3,940216,152900,air,10m,G-024,3,10.0,40.00,32.92,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,,,,
4,940216,180000,air,10m,G-024,3,10.0,40.00,33.31,NaN,...,NaN,NaN,NaN,NaN,NaN,1692.489,F,F,,

In [80]:
mhd_df.tail()

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,...,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
817950,260518,65300,std,J-286,J-286,3,0.0,40.0,22.06,NaN,...,NaN,NaN,NaN,3.649,NaN,2015.923,,,A,
817951,260518,71300,air,9m,J-286,1,9.0,40.0,22.32,NaN,...,2061.71,2025.82,2025.82,3.649,3.666,2015.923,,,A,
817952,260518,73300,std,J-286,J-286,3,0.0,40.0,22.19,NaN,...,2159.17,2716.92,2716.92,4.605,NaN,2015.923,,,A,
817953,260518,75300,air,9m,J-286,1,9.0,40.0,22.10,NaN,...,1955.78,1676.37,NaN,4.605,NaN,2015.923,*,*,A,
817954,260518,81300,std,J-286,J-286,3,0.0,40.0,22.23,NaN,...,NaN,NaN,NaN,14.873,NaN,2015.923,,,A,

In [6]:
mhd_df.iloc[[185]]

,date,time,type,sample,standard,port,ht,tmod,tamb,temp,pflow,psamp,ploop,pamb,rt,w,ht,area,skew,start_time,end_time,start_level,end_level,Rl_ht,Rl_a,Rl,norm_ht,norm_a,norm_w,R_ht,R_a,R,C_ht,C_a,C,std_stdev,std_rep,Cstd,flag_ht,flag_a,flag,flag_p
185,940219,102700,cal1060,G-024,G-024,1,0.0,40.01,23.16,NaN,846.8,1058.3,NaN,751.2,95.2,7.51,205489.0,1651923.0,1.0,82.6,130.2,30872.0,30727.0,0.92736,1.00177,0.92736,1.3073,1.4122,1.0901,0.92736,1.00177,0.92736,1569.54,1695.49,1692.49,3.18,NaN,1692.489,,,,

#### optical data

In [ ]:
import pandas as pd
import numpy as np


file_path = "../data/raw/tac_ch4.txt"

df_tac = pd.read_csv(file_path, skiprows=1, sep=r'\s+', header=1) 
# skip first row, txt is space seperated

In [ ]:
def split_flag (val):
    if pd.isna(val):
        return np.nan, np.nan
    
    val_str = str(val).strip()
    # check if last val is a character(Flag)
    if val_str[-1].isalpha() or val_str[-1] == '*':
        c_val = float(val_str[:-1])
        flag_val = val_str[-1]
    else:
        c_val = float(val_str) # normal value, then direcly convert to float
        flag_val = " " # no flag, give it a space
    
    return c_val, flag_val

In [ ]:
df_tac['C'], df_tac['ch4_flag'] = zip(*df_tac['C'].map(split_flag))
df_tac.columns = feature_name_tacch4
df_tac.to_csv("../data/processed/tac_ch4_formatted_v1.csv", index=False)